language: java

cache:
  directories:
  - $HOME/.m2

matrix:
  include:
    - jdk: oraclejdk8
      env:
        - DESC="verifications"
      script: mvn verify

    - jdk: oraclejdk8
      env:
        - DESC="static analysis"
      # skip integration tests
      script: mvn test cobertura:cobertura
      after_success:
        # push report to codecov server
        bash <(curl -s https://codecov.io/bash)
